[package]
name = "hann-rs"
version = "0.1.0"
edition = "2021"
authors = ["F0rty-Tw0 <artiomtofancv@gmailcom>"]
description = "Blazingly fast Rust Hann Window"
license = "MIT"
repository = "https://github.com/F0rty-Tw0/hann-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]

[dev-dependencies]
criterion = "0.4"
