[package]
name = "hann-rs"
version = "0.1.0"
edition = "2021"
authors = ["Artiom Tofan <artiomtofancv@gmailcom>"]
description = "Blazingly fast Rust Hann Window"
license = "MIT"
repository = "https://github.com/F0rty-Tw0/hann-rs"
readme = "README.md"
keywords = ["hann-window", "signal-processing", "dsp", "audio", "fft"]
categories = ["audio", "science", "mathematics"]

[lib]
name = "hann_rs"
path = "src/lib.rs"
crate-type = ["lib"]

[dependencies]
lazy_static = "1.4"


[dev-dependencies]
criterion = "0.4"
approx = "0.5.1"


[[bench]]
name = "bench"
harness = false
